_target_: pytorch_lightning.trainer.Trainer
max_epochs: null
max_steps: 5000
accelerator: gpu
limit_train_batches: 1
log_every_n_steps: 10
check_val_every_n_epoch: 500
devices:
  - 7
precision: 32
deterministic: True
enable_checkpointing: true
fast_dev_run: false
enable_progress_bar: true