program: src/train.py
method: random
metric:
  goal: maximize
  name: validation/mean_ccc.max
parameters:
  logger.wandb.mode: 
    value: "online"
  data.radius: 
    values: [0.04, 0.05, 0.06]
    distribution: categorical
  data.st_path:
    value: ${paths.data_dir}/spatial/simulations_kidney_slideSeq_v2/UMOD-WT.WT-2a_resolution75.h5ad
  data.reference_dir:
    value: ${paths.root_dir}/experiments/experiment_kidney_slideSeq_v2_UMOD-WT.WT-2a_resolution75
  model.alpha_max: 
    min: 0.1
    max: 0.5
    distribution: uniform
  model.alpha_min:
    min: 0.0
    max: 0.1
    distribution: uniform
  model.learning_rate:
    min: 1.0e-5
    max: 1.0e-3
    distribution: uniform
  model.beta:
    values: ["None", 0.0, 5.0, 10.0]
    distribution: categorical
  model.l1_lambda:
    min: 0.0
    max: 1.0e-5
    distribution: uniform
  model.l2_lambda:
    min: 0.0
    max: 1.0e-5
    distribution: uniform
  model.weight_decay:
    min: 0.0
    max: 1.0e-5
    distribution: uniform
  net.latent_dim:
    values: [128]
    distribution: categorical
  net.activation:
    values: ["relu6"]
    distribution: categorical
  net.use_pos:
    values: [True]
    distribution: categorical
  # net.use_id:
  #   values: [True, False]
  #   distribution: categorical
  net.encoder_type:
    value: "gnn"
  net.encoder_kwargs.norm:
    values: ["None", "batch_norm"]
    distribution: categorical
  net.encoder_kwargs.fusion:
    values: ["", "concat", "concat_skip", "concat_simple"]
    distribution: categorical
  net.encoder_kwargs.use_ffn:
    values: [False, True]
    distribution: categorical
  net.encoder_kwargs.spatial_channel:
    value: True
  net.encoder_kwargs.lin_channel:
    values: [False, True]
    distribution: categorical
  net.encoder_kwargs.num_layers:
    values: [1, 2, 3]
    distribution: categorical



command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}